### ISSUE TITLE
Try catch all exception in Knowhere to avoid threadpool crashes 

### ISSUE THREAD

**Issue by liliu-z** [zilliztech/knowhere#804]
Looks like we get many places didn't take care of the exception throwing like https://github.com/zilliztech/knowhere/blob/613f06f15597ff0abea79801c6995af5e2fb7713/src/common/comp/brute_force.cc#L136
We need to try catch is to avoid folly thread crash.

_Originally posted by @liliu-z in https://github.com/zilliztech/knowhere/issues/802#issuecomment-2320623790_

**Comment by alexanderguzhva** [comment]
@liliu-z @cydrain  I disagree. Such throws are in design of `WaitAllSuccess()` and ARE expected in case of unexpected situations, such as a program bug. What is needed is to make sure that all corner cases  are handled, instead of masking them by using `try\catch` and having unreported problems in the code. Alternative, we may switch to using `std::optional<>` data type

**Comment by liliu-z** [comment]
> WaitAllSuccess

I didn't make myself clear. My point of view is `try/catch` and then use `expected` to get error code out.
There are two different kinds of error report methods, `error code` and `exception`. Knohwere adapts `error code` at beginning and I am trying to align all scenarios.
